[workspace]
members = ["crate/*"]
default-members = ["crate/wurstminebot-cli"]
resolver = "2"

[workspace.package]
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[profile.release]
lto = true
strip = true
