[package]
name = "wurstminebot"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "wurstminebot"
path = "src/lib.rs"

[[bin]]
name = "wurstminebot"
path = "src/main.rs"
doc = false
test = false
bench = false

[dependencies]
serde = "1"
serde_derive = "1"
serde_json = "1"
serenity = "*"
typemap = "*"
wrapped_enum = "*"
