[package]
name = "wurstminebot-ipc"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "wurstminebot_ipc"
path = "src/lib.rs"

[dependencies]
serenity = "0.9"

[dependencies.wurstminebot]
path = "../wurstminebot"

[dependencies.serenity-utils]
git = "https://github.com/fenhl/serenity-utils" #TODO publish to crates.io
branch = "main"
