[package]
name = "wurstminebot"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[dependencies]
itertools = "0.10"
lazy_static = "1"
pin-utils = "0.1"
rand = "0.8"
regex = "1"
serde_json = "1"
serenity = "0.10"
uuid = "0.8"

[dependencies.chase]
version = "0.1"
features = ["stream"]

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.diesel] #TODO use something async instead?
version = "1"
features = ["postgres", "serde_json"]

[dependencies.futures]
version = "0.3"
features = ["compat"]

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serenity-utils]
git = "https://github.com/fenhl/serenity-utils" #TODO publish to crates.io
branch = "main"

[dependencies.systemd_minecraft]
git = "https://github.com/wurstmineberg/systemd-minecraft"
branch = "riir"
package = "minecraft"

[dependencies.tokio]
version = "1.3"
features = ["fs", "macros", "rt-multi-thread"]

[dependencies.tokio-stream]
version = "0.1"
features = ["io-util"]

[dependencies.twitchchat]
#version = "0.14"
git = "https://github.com/museun/twitchchat" #TODO switch back to crates.io once tokio 1 is supported
rev = "6292ca3c523bcb31a2c746aaae88439fd0fb4c55"
default-features = false
features = ["async", "tokio", "tokio-rustls", "tokio-util", "webpki-roots"]
