[package]
name = "wurstminebot"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2021"

[dependencies]
futures = "0.3"
itertools = "0.10"
lazy-regex = "2"
rand = "0.8"
serde_json = "1"
serenity = "0.10"

[dependencies.derive_more]
version = "0.99"
default-features = false
features = ["from"]

[dependencies.discord-message-parser]
git = "https://github.com/fenhl/discord-message-parser"
branch = "main"

[dependencies.minecraft]
git = "https://github.com/wurstmineberg/rust-minecraft-types"
branch = "main"

[dependencies.serde]
version = "1"
features = ["derive"]

[dependencies.serenity-utils]
git = "https://github.com/fenhl/serenity-utils" #TODO publish to crates.io?
branch = "main"

[dependencies.sqlx]
version = "0.5"
default-features = false
features = ["json", "macros", "postgres", "runtime-tokio-rustls"]

[dependencies.systemd_minecraft]
git = "https://github.com/wurstmineberg/systemd-minecraft"
branch = "riir"
package = "minecraft"

[dependencies.tokio]
version = "1.3"
features = ["fs", "macros", "rt-multi-thread"]

[dependencies.twitch_helix]
git = "https://github.com/fenhl/rust-twitch-helix" #TODO publish to crates.io
branch = "main"

[dependencies.twitchchat]
#version = "0.14"
git = "https://github.com/museun/twitchchat" #TODO switch back to crates.io once tokio 1 is supported
rev = "6292ca3c523bcb31a2c746aaae88439fd0fb4c55"
default-features = false
features = ["async", "tokio", "tokio-rustls", "tokio-util", "webpki-roots"]

[target.'cfg(unix)'.dependencies]
uuid = "0.8"

[target.'cfg(unix)'.dependencies.chase]
version = "0.1"
features = ["stream"]

[target.'cfg(unix)'.dependencies.futures]
version = "0.3"
features = ["compat"]

[target.'cfg(unix)'.dependencies.tokio-stream]
version = "0.1"
features = ["io-util"]
