[package]
name = "wurstminebot-python"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[lib]
name = "wurstminebot"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies.wurstminebot-ipc]
path = "../wurstminebot-ipc"

[dependencies.pyo3]
version = "0.11"
features = ["extension-module"]

[dependencies.serenity]
version = "0.8"
default-features = false
features = ["model", "utils"]
