[package]
name = "wurstminebot-cli"
version = "0.1.0"
authors = ["Fenhl <fenhl@fenhl.net>"]
edition = "2018"

[[bin]]
name = "wurstminebot"
path = "src/main.rs"
doc = false
test = false
bench = false

[dependencies]
chrono = "0.4"
parking_lot = "0.9" # because serenity still uses 0.9
serenity = "0.8"
typemap = "0.3"

[dependencies.diesel]
version = "1"
features = ["postgres", "serde_json"]

[dependencies.shlex]
git = "https://github.com/fenhl/rust-shlex"

[dependencies.systemd_minecraft]
git = "https://github.com/wurstmineberg/systemd-minecraft"
branch = "riir"
package = "minecraft"

[dependencies.tokio]
version = "0.2"
features = ["fs", "macros", "rt-threaded"]

[dependencies.wurstminebot]
path = "../wurstminebot"
